version: '3.8'

services:
  frontend:
    build:
      context: /home/gouthamur/IdeaProjects/SPE_Final
      dockerfile: Dockerfile  # Use this if your Dockerfile is named "Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: /home/gouthamur/IdeaProjects/FS/src/main/java/org/example/fullstack-frontend
      dockerfile: Dockerfile  # Use this if your Dockerfile is named "Dockerfile"
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3307"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
